FROM node:8

ARG CLIENT_PROTOCOL
ARG CLIENT_HOST
ARG CLIENT_PORT
ARG SERVER_PROTOCOL
ARG SERVER_HOST
ARG SERVER_PORT

ENV CLIENT_PROTOCOL=$CLIENT_PROTOCOL
ENV CLIENT_HOST=$CLIENT_HOST
ENV CLIENT_PORT=$CLIENT_PORT
ENV SERVER_PROTOCOL=$SERVER_PROTOCOL
ENV SERVER_HOST=$SERVER_HOST
ENV SERVER_PORT=$SERVER_PORT

RUN mkdir -p /src
WORKDIR /src
COPY app/ .
RUN npm install

CMD npm run start-docker

EXPOSE $SERVER_PORT