version: '3'
services:
  admin-backend:
    build:
      context: .
      args:
        - CLIENT_PROTOCOL=${CLIENT_PROTOCOL}
        - CLIENT_HOST=${CLIENT_HOST}
        - CLIENT_PORT=${CLIENT_PORT}
        - SERVER_PROTOCOL=${SERVER_PROTOCOL}
        - SERVER_HOST=${SERVER_HOST}
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    network_mode: "host"